app: Fixed typos in STM32CubeIDE files
TheThingsIndustries/generic-node-se pull request #126
Opened 2021-02-22 14:34 UTC by marnixcrouzen

**Summary:**

STM32CubeIDE will not build on Linux due to small capitalisation typos in the .cproject files. Closes #125.

**Changes:**

- Capitalised all instances of 'include'

**Notes for Reviewers:**

Check on your OS if the changed didn't affect your build.

2021-02-22 14:50 UTC, elsalahy requested changes
@marnixcrouzen Please respect the [commit guideline](https://discuss.thethingsindustries.com/t/embedded-development-guideline/104).
This commit should be:
`dev: Fix .......`

Please don't close this PR, and do a reward and force push of the commit

2021-02-22 16:10 UTC, elsalahy submitted a review, later dismissed

2021-02-23 09:00 UTC, marnixcrouzen commented
After re-review with STM32CubeIDE I found that one change was not necessary (it did build yesterday, but not after deleting the project and readding it) so I amended the commit to only fix the wrong files.

2021-02-23 09:11 UTC, elsalahy approved these changes

2021-02-23 09:16 UTC, merged