lib: Add configurable speed options for I2C/SPI
TheThingsIndustries/generic-node-se pull request #135
Opened 2021-03-04 16:13 UTC by marnixcrouzen

**Summary:**

The clock speeds for both the I2C and SPI interface were made more configurable and clear. Only I2C device that could not handle 300 kHz was the secure element. These apps were tested and worked normally: basic, basic_lorawan, freefall_lorawan. Speeds were calculated with STM32CubeMX and tested afterwords with a logic analyzer. Closes #39.

**Changes:**

- Increased the speeds for I2C and SPI to their functional maximum
- Added more defines for the I2C clock speeds
- SPI clock speeds were documented better

2021-03-10 14:50 UTC, marnixcro commented on Software/lib/GNSE_BSP/GNSE_bsp_serial.h
> +#define SENSOR_I2C1_TIMING           I2C_SPEED_FMP_300_KHZ
Good to know, thx! I've changed the enums to defines

2021-03-10 14:53 UTC, marnixcro commented
> I haven't tested this yet, but I plan to, did you try one of these configurations with the basic_lorawan app?

I've tested with freefall_lorawan, which is basically the same (+ it uses the I2C for the accelerometer). I tested just now to be sure and it seemed to work as usual.

2021-03-12 10:08 UTC, elsalahy requested changes

2021-03-12 10:08 UTC, elsalahy commented on Software/lib/GNSE_BSP/GNSE_bsp_serial.h
> +#define SENSOR_I2C1_TIMING           0x0020088D
```suggestion
#define SENSOR_I2C1_TIMING           0x0020088DU
```

2021-03-12 10:08 UTC, elsalahy commented on Software/lib/GNSE_BSP/GNSE_bsp_serial.h
> +#define EXT_SENSOR_I2C2_TIMING           0x20003D5E
```suggestion
#define EXT_SENSOR_I2C2_TIMING           0x20003D5EU
```

2021-03-12 10:08 UTC, elsalahy commented on Software/lib/GNSE_BSP/GNSE_bsp_serial.h
> + * Changing any of these variables without reconfiguring this define could break the I2C communication
I like this explanation, well done 👍

2021-03-12 10:08 UTC, elsalahy commented on Software/lib/GNSE_BSP/GNSE_bsp_serial.h
> + */
I don't think this is necessary, let's remove it as well and add a small comment on the current default, same as the I2C

2021-03-12 10:08 UTC, elsalahy commented on Software/lib/GNSE_BSP/GNSE_bsp_serial.h
> +#define FLASH_SPI_BAUDRATE            SPI_BAUDRATEPRESCALER_2
```suggestion
#define FLASH_SPI_BAUDRATE            SPI_BAUDRATEPRESCALER_16
```

2021-03-12 10:08 UTC, elsalahy commented on Software/lib/GNSE_BSP/GNSE_bsp_serial.h
> +#define FLASH_SPI_BAUDRATE            SPI_BAUDRATEPRESCALER_2
I think we should default this to lower speeds until we extensively test this

2021-03-12 10:38 UTC, elsalahy approved these changes
Great

2021-03-12 10:41 UTC, merged