SE randomizer support
TheThingsIndustries/generic-node-se pull request #192
Opened 2021-06-04 09:45 UTC by marnixcro

**Summary:**

This adds the secure element's randomizer for generating random numbers. Additionally adds tags to gitignore. Closes #137 and #191.

**Changes:**

- Adds randomizer functionality, which also makes sure that the SE is on as it would otherwise be stuck
- Replaces the instance the randomizer was needed (previously used with radio randomize feature)
- Added 'tags' to gitignore

**Notes for Reviewers:**

Best is to print out the resulting 'rand_in' variables and see these change. Of course, it should join with the OTAA as well.

2021-06-07 14:17 UTC, elsalahy requested changes
Great, thanks for implementing this.
Can you please remove this header as well 
https://github.com/TheThingsIndustries/generic-node-se/blob/031dd1e1d2e2bd802e5900b696c674579ce72ae7/Software/lib/ATECC608A-TNGLORA/atecc608a-tnglora-se.c#L43
Will do onboard testing once these changes are addressed.

2021-06-07 14:17 UTC, elsalahy commented on Software/lib/ATECC608A-TNGLORA/atecc608a-tnglora-se-hal.c
> +    }
This section should not part of SE HAL
The device driver implementation assumes a powered device and this is the function of the LPM to synchronize sensor activation with secure element requests.

2021-06-07 14:17 UTC, elsalahy commented on Software/lib/ATECC608A-TNGLORA/atecc608a-tnglora-se-hal.c
> +    }
As I mentioned above.

2021-06-08 09:48 UTC, elsalahy commented
@marnixcro any reason why you didn't remove the header mentioned in my previous comment?

2021-06-08 10:10 UTC, marnixcro commented
> @marnixcro any reason why you didn't remove the header mentioned in my previous comment?

No, I forgot to edit it

2021-06-09 05:35 UTC, elsalahy commented
I'm unable to test OTAA due to entity not found issues (unrelated to secure element), can your device join OTAA successfully?

2021-06-09 05:43 UTC, elsalahy commented
The join server license seems to have expired, will test again when it is renewed by ops team

2021-06-09 06:42 UTC, elsalahy approved these changes
Tested and secure_element_lorawan OTAA joins are functional
LGTM

2021-06-09 07:19 UTC, merged